### ISSUE TITLE
Lacking '/home/dj/Cheetah-Software/build/user/MIT_Controller/libuser_controller.so'

### ISSUE THREAD

**Issue by USTCzzl** [GTLIDAR/ltl_multi_agent#1]
Thank you very much for your great work on open source，But there seems to be some problems here. when I try to compile, I find a lack of dependencies [Cheetah Software](https://github.gatech.edu/login?return_to=https%3A%2F%2Fgithub.gatech.edu%2FGeorgiaTechLIDARGroup%2FCheetah-Software), Is there any way to clone this link？

**Comment by zzhou387** [comment]
Thank you for reporting this. I have open sourced it [here](https://github.com/GTLIDAR/Cheetah-Software).  Please remeber to checkout to the ltl_supported branch. The README for this repo has been updated as well. Currently the compile process is a little bit convoluted because of the low-level controller for quadruped. We will release a version without the quadruped dependency in the future. Let me know if you have any other compiling issues.

**Comment by USTCzzl** [comment]
@zzhou387 Thank you for your reply, the compilation process is fine, but when I try to run the demo(roslaunch ltl_automaton_planner_study_2), I find that gazebo keeps saying that it is in loading state and cannot display the image properly. I have an error viewing the haircut robotmodel from rviz, it seems to be a missing TF issue.
![181640157316_ pic](https://user-images.githubusercontent.com/35604404/147051625-7ebadefc-fc53-4edf-919c-11bded2954c5.jpg)

**Comment by zzhou387** [comment]
The gazebo loading issue is caused by missing mesh files that we defined in the hospital scenario. I'll fix this very soon and update you here.

As for the missing transformation, can you try launching the entire launch file again? The model for quadruped A1 doesn't get spawned correctly sometimes. If that still doesn't work, can you run `rosrun tf view_frames` and take a screenshot of the generated frames.pdf for me? also, which ros version are you using right now?

**Comment by USTCzzl** [comment]
@zzhou387 Thanks for your reply,  here is my frames.pdf, I am using ROS Melodic, gazebo11
![191640677311_ pic](https://user-images.githubusercontent.com/35604404/147541681-9c440927-4ab2-4895-91ba-d304e1afbfad.jpg)

**Comment by zzhou387** [comment]
Sorry about the delay. It is very likely to be caused by the world file loading issue. I just uploaded a [branch](https://github.com/GTLIDAR/gazebo_models/tree/hospital_scenario) called `hospital_scenario` with all the gazebo models used in our environment (including some other unused models so it's a little bit large in total. not great but should work). Can you simply copy these models into your local gazebo model path `~/.gazebo/models`? Then run the launch file again see whether the above problems get fixed?

**Comment by USTCzzl** [comment]
@zzhou387 I tried what you said, but still can't solve the problem. gazebo can open normally, but will soon flash back, the main error is still can't load the unitree.

**Comment by zzhou387** [comment]
apologize for the late response. can you copy the terminal log for me?

**Comment by USTCzzl** [comment]
@zzhou387 Thank you for your reply！
[study_2.log](https://github.com/GTLIDAR/ltl_multi_agent/files/8170520/study_2.log)
The main problem should be that A1 can't be imported and gazebo will flash soon after opening. If you comment out a1, gazebo can open normally, but it lacks many scenes, only the hospital and two robots and one person. It is worth noting that your previously released Cheetah-software running common/test_common does not work completely and can pass 17/18.
[cheetah.log](https://github.com/GTLIDAR/ltl_multi_agent/files/8170531/cheetah.log)

**Comment by USTCzzl** [comment]
@zzhou387 There is also the fact that I used gazebo-9 because the previous unitree compilation required gazebo-8 and did not follow the recommended gazebo-11, but this does not seem to be the cause of the error

**Comment by zzhou387** [comment]
Thanks for reporting the cheetah test. However, that error is expected and won't affect anything. I don't think it was any A1 modules that caused the problem. To quickly test it, you can run a simple scenario with only A1 spawned:
```
$ roslaunch unitree_bringup unitree_spawn.launch 
```
another terminal run the controller:
```
$ rosrun quadruped_ctrl a1_servo
```
If you want to test different locomotion modes (2 is to start trotting), do:
```
$ rosservice call /ControlMode 2
```
If you see A1 trotting normally then you are good.

I have found out that the TF error was caused by the renaming of "fixed_fram_id" in mocap simulator's launch file. That bug has been fixed and the TF error should be gone. 

Another bug I fixed was coming from the BT node when loading the yaml file. An update was accidentally pushed months ago. This might cause the flashing out problem that you encountered before. Can you pull the latest code and see whether that problem gets fixed? 

In terms of the missing gazebo models, there were a few models that failed to be uploaded but I didn't notice. I am still working on that and I apologize for the inconvenience.

**Comment by USTCzzl** [comment]
@zzhou387 Thank you for your reply, I tried it as you said 

> roslaunch unitree_bringup unitree_spawn.launch 

Basically everything is normal, but i tried

> roslaunch ltl_automaton_planner study_2.launch

I get a reported error : **Connectivity Error looking up robot pose: Could not find a connection between 'map' and 'wassi_0/base_footprint' because they are not part of the same tree.Tf has two or more unconnected trees.**

Now gazebo no more flashback， the robotmodel on the rviz is still wrong, so rviz can't display A1's joints 

![3](https://user-images.githubusercontent.com/35604404/156881256-f6b3108d-a327-49da-bdb8-cde82f6f5b60.png)
But it can be displayed normally in the gazebo, that is, it is always in the lying down mode

![2](https://user-images.githubusercontent.com/35604404/156881291-7bfc0c7e-4799-4dbc-8c80-fa1c068359c3.png)

The last problem, as you said, may be the lack of some models
![1](https://user-images.githubusercontent.com/35604404/156881324-5105a2f3-81af-451c-bae0-c0b4f35807ce.png)

Finally attached the system tf chart, very much looking forward to your update, thanks

[frames.pdf](https://github.com/GTLIDAR/ltl_multi_agent/files/8190572/frames.pdf)

**Comment by zzhou387** [comment]
For some reason the previous repo runs into some git issues, I have updated the gazebo models [here](https://github.com/zzhou387/gazebo_models). As for the A1 joint issue, it might be caused by the missing models as well. If gazebo takes a long time to start then the ros controller plugins provided by unitree might not be initialized correctly. Can you download the newly updated gazebo models and see whether that fixes the problem?

**Comment by USTCzzl** [comment]
@zzhou387 As per your update, everything seems to be working fine, but this task doesn't seem to be the same as the video you released, I'll look into your paper and code more specifically, thank you！
